language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip3 install -U platformio
    - platformio update
    - platformio lib install

before_script:
    - cp .travis.config.h src/config.h

script:
    - platformio run -e lolin32
